### ISSUE TITLE
Not ready for release yet

### ISSUE THREAD

**Issue by LappleApple** [zalando/toga#1]
Hey -- without a clear README this project isn't so useful to the public yet and should be removed from the org page. You should feel free to develop this on your own account and then push it to the org when it's in a ready state. Let me know if you need guidance/info.

**Comment by JonasJurczok** [comment]
As far as I know you cannot transfer issues from one project to the other. So if I start in my account now and then push it at some point to the zalando account the whole issue history will be lost.

**Comment by LappleApple** [comment]
I did some asking for you (and for others, it turns out!) and actually you can transfer issues, if you also transfer ownership of a repo to another organization :)

**Comment by JonasJurczok** [comment]
Ah okay. Good to know. Thank you :)

Then I consider moving it into my personal space until there is something usable if I cannot reach that state tomorrow afternoon. Deal? :)

**Comment by LappleApple** [comment]
Yeah, sounds like a plan! )

**Comment by JonasJurczok** [comment]
Closing after discussion in person :)
Thanks again for the input @LappleApple
